/* SolarPilot 1.0.0-beta.49. Local option explanations + HA's native options-flow API.
 * No actuator service is called here. HA retains authentication, schema validation,
 * per-device live/deferred guards and final config-entry save. No internal HA DOM is patched.
 */
let spOptionHelpPromise;
async function spOptionHelp(){
  if(globalThis.SOLAR_PILOT_HELP_DATA)return globalThis.SOLAR_PILOT_HELP_DATA;
  if(!spOptionHelpPromise)spOptionHelpPromise=fetch('/solar_pilot_static/option-help.json?v=1.0.0-beta.49',{credentials:'same-origin'})
    .then(r=>{if(!r.ok)throw new Error('De lokale optie-uitleg kon niet worden geladen.');return r.json();})
    .catch(e=>{spOptionHelpPromise=null;throw e;});
  return spOptionHelpPromise;
}
const spHelpEscape=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const spHelpStyle=`:host{font:14px/1.55 system-ui,sans-serif;color:var(--primary-text-color,#e8edf2)}*{box-sizing:border-box}dialog{color:inherit;background:var(--card-background-color,#20242a);border:1px solid var(--divider-color,#606874);border-radius:18px;padding:0;width:min(760px,calc(100vw - 24px));max-width:none;max-height:calc(100dvh - 24px);box-shadow:0 18px 70px #0008}dialog::backdrop{background:#0008}header{position:sticky;top:0;background:inherit;display:flex;align-items:center;gap:16px;padding:16px 20px;border-bottom:1px solid var(--divider-color,#606874);z-index:1}h2{margin:0;font-size:19px;line-height:1.4;flex:1;overflow-wrap:anywhere}.body{padding:16px 20px;overflow-wrap:anywhere}p{margin:0 0 14px}.muted{font-size:12px;color:var(--secondary-text-color,#a9b3bf)}button{font:inherit;cursor:pointer;color:inherit;background:transparent;border:1px solid var(--divider-color,#606874);padding:9px 13px;border-radius:10px;min-height:40px}button:hover{background:var(--secondary-background-color,#313842)}button:disabled{opacity:.45;cursor:default}button:focus-visible,input:focus-visible,select:focus-visible{outline:3px solid var(--primary-color,#03a9f4);outline-offset:2px}.close{font-size:23px;width:42px;padding:2px}.help{border-radius:50%;width:30px;min-height:30px;padding:0;flex:none;font-weight:700}.error{color:var(--error-color,#ff8b8b);white-space:pre-wrap}.description{white-space:pre-wrap}.field{margin:0 0 18px}.label{display:flex;gap:10px;align-items:center;margin-bottom:7px}.label label{flex:1}input:not([type=checkbox]),select{font:inherit;color:inherit;background:var(--secondary-background-color,#2b323b);border:1px solid var(--divider-color,#606874);border-radius:8px;width:100%;min-height:42px;padding:8px;max-width:100%}input[type=checkbox]{width:23px;height:23px;accent-color:var(--primary-color,#03a9f4)}.check{display:flex;align-items:center;gap:10px}select[multiple]{min-height:105px}.menu{display:grid;gap:9px}.menu button{text-align:left}.actions{display:flex;gap:10px;margin-top:22px;flex-wrap:wrap}.primary{background:var(--primary-color,#0284c7);color:var(--text-primary-color,#fff)}a{color:var(--primary-color,#58b6fa)}.wait{padding:18px 0}.inline-error{font-size:12px;min-height:18px}@media(max-width:500px){header,.body{padding:14px}dialog{border-radius:13px;width:calc(100vw - 12px);max-height:calc(100dvh - 12px)}h2{font-size:17px}}`;
class SolarPilotOptionHelpDialog extends HTMLElement{
  static catalog(){return spOptionHelp();}
  constructor(){super();this.attachShadow({mode:'open'});this.shadowRoot.innerHTML=`<style>${spHelpStyle}</style><dialog aria-labelledby="help-title"><header><h2 id="help-title">Uitleg</h2><button class="close" type="button" aria-label="Uitleg sluiten">×</button></header><div class="body"></div></dialog>`;this.dialog=this.shadowRoot.querySelector('dialog');this.shadowRoot.querySelector('button').onclick=()=>this.close();this.dialog.addEventListener('click',e=>{if(e.target===this.dialog){const r=this.dialog.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)this.close();}});}
  async open(step,key,title){this._token=(this._token||0)+1;const token=this._token;this.shadowRoot.querySelector('h2').textContent=title||'Uitleg';this.shadowRoot.querySelector('.body').textContent='Uitleg laden…';if(!this.dialog.open)this.dialog.showModal();try{const data=await spOptionHelp();if(token!==this._token||!this.dialog.open)return;const item=data.entries[`${step}.${key}`]||Object.entries(data.entries).find(([id])=>id.endsWith(`.${key}`))?.[1];this.shadowRoot.querySelector('h2').textContent=item?.title||title||key;this.shadowRoot.querySelector('.body').innerHTML=(item?.paragraphs||['Voor dit veld ontbreekt de release-uitleg. Laat de huidige waarde staan en raadpleeg de actuele werking.']).map(t=>`<p>${spHelpEscape(t)}</p>`).join('')+`<p class="muted">Uitleg bij SolarPilot ${spHelpEscape(data.version)} · geen bedieningsopdracht</p>`;}catch(e){this.shadowRoot.querySelector('.body').textContent=e.message||String(e);}}
  close(){this._token=(this._token||0)+1;if(this.dialog.open)this.dialog.close();}
  disconnectedCallback(){this.close();}
}
if(!customElements.get('solar-pilot-option-help-dialog'))customElements.define('solar-pilot-option-help-dialog',SolarPilotOptionHelpDialog);

class SolarPilotOptionsDialog extends HTMLElement{
  constructor(){super();this.attachShadow({mode:'open'});this._busy=false;this._open=false;this._seq=0;this._dirty=false;this._draftStarted=false;this._menuPath=[];this._formParent=[];this.shadowRoot.innerHTML=`<style>${spHelpStyle}header .back{white-space:nowrap;flex:none}@media(max-width:500px){header{gap:8px}header .back{padding:8px;font-size:12px}}</style><dialog aria-labelledby="options-title"><header><button class="back" type="button" aria-label="Terug naar SolarPilot">‹ Terug</button><h2 id="options-title">SolarPilot · configureren</h2><button class="close" type="button" aria-label="Configuratie sluiten">×</button></header><div class="body"><div class="content"></div><p class="error" role="alert"></p><p class="muted">Alleen opslaan kan instellingen wijzigen. De server bewaakt toestemming en grenzen; gevoelige wijzigingen wachten op een veilige toesteltoestand. <a href="/config/integrations/integration/solar_pilot">Standaard Home Assistant-configuratie</a></p></div></dialog>`;this.dialog=this.shadowRoot.querySelector('dialog');this.content=this.shadowRoot.querySelector('.content');this.error=this.shadowRoot.querySelector('.error');this.shadowRoot.querySelector('.close').onclick=()=>this.close();this.shadowRoot.querySelector('.back').onclick=()=>this._back();this.shadowRoot.addEventListener('click',e=>this._click(e));for(const type of ['input','change'])this.shadowRoot.addEventListener(type,e=>{if(e.target.closest('form')&&e.target.name)this._dirty=true;});this.shadowRoot.addEventListener('submit',e=>{e.preventDefault();this._submit(e.target);});this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});}
  async open(hass,entryId,route=[]){if(this._open)return;this.hass=hass;this.entryId=entryId;this._open=true;this._dirty=false;this._draftStarted=false;this._menuPath=[];this._formParent=[];this.flow=null;this.error.textContent='';this.content.innerHTML='<p class="wait">Configuratie laden…</p>';this.dialog.showModal();if(!hass.user?.is_admin){this.content.innerHTML='<p>Alleen een Home Assistant-beheerder kan configuratie wijzigen.</p>';return;}try{this.help=await spOptionHelp();if(!this._open)return;await this._request('config/config_entries/options/flow',{handler:entryId});for(const payload of route){if(!this._open||!this.flow?.flow_id)break;if(payload.next_step_id&&!this.flow.menu_options?.includes(payload.next_step_id))break;await this._request(`config/config_entries/options/flow/${encodeURIComponent(this.flow.flow_id)}`,payload);}}catch(e){this.error.textContent=e.message||String(e);}}
  _discard(){return!(this._dirty||this._draftStarted)||window.confirm('Niet-opgeslagen wijzigingen weggooien?');}
  async close(force=false){if(this._busy||!force&&!this._discard())return false;this._open=false;this._seq++;this._dirty=false;this._draftStarted=false;this.helpDialog?.close();if(this.dialog.open)this.dialog.close();const id=this.flow?.flow_id;this.flow=null;if(id)try{await this.hass.callApi('delete',`config/config_entries/options/flow/${encodeURIComponent(id)}`);}catch(_){/* already completed / disconnected */}return true;}
  async _back(){
    if(this._busy||!this._open)return;if(this.uiHistory?.back(this))return;const path=this.flow?.type==='menu'?this._menuPath.slice(0,-1):[...this._formParent];
    if(this.flow?.step_id==='init'||!this.flow||this.flow.type==='create_entry'||this.flow.type==='abort')return this.close();
    if(!this._discard())return;const id=this.flow?.flow_id;this._busy=true;this._controls(true);this.error.textContent='';
    try{if(id)await this.hass.callApi('delete',`config/config_entries/options/flow/${encodeURIComponent(id)}`);}catch(e){this.error.textContent='Teruggaan niet bevestigd. Je invoer blijft staan: '+(e.message||String(e));this._busy=false;this._controls(false);return;}
    this._busy=false;this._dirty=false;this._draftStarted=false;this._menuPath=[];this._formParent=[];this.flow=null;this.content.innerHTML='<p class="wait">Instellingenoverzicht laden…</p>';
    await this._request('config/config_entries/options/flow',{handler:this.entryId});
    for(const next_step_id of path){if(!this._open||this.flow?.type!=='menu'||!this.flow.menu_options?.includes(next_step_id))break;await this._request(`config/config_entries/options/flow/${encodeURIComponent(this.flow.flow_id)}`,{next_step_id});}
  }
  _controls(disabled){this.shadowRoot.querySelectorAll('.close,.back').forEach(e=>e.disabled=disabled);this.content.querySelectorAll('button,input,select').forEach(e=>{if(!e.dataset.permanentDisabled)e.disabled=disabled;});}
  disconnectedCallback(){if(!this._busy)this.close();else{this._open=false;this._seq++;this.helpDialog?.close();}}
  async _request(path,data){if(this._busy||!this._open)return;this._busy=true;this.error.textContent='';const seq=++this._seq;this._controls(true);try{const result=await this.hass.callApi('post',path,data);if(seq!==this._seq||!this._open){if(result?.flow_id)try{await this.hass.callApi('delete',`config/config_entries/options/flow/${encodeURIComponent(result.flow_id)}`);}catch(_){}return;}if(data?.next_step_id){const parent=[...this._menuPath];if(result.type==='menu')this._menuPath=[...parent,data.next_step_id];else this._formParent=parent;}this.flow=result;this._render();if(data?.next_step_id){const route=(result.type==='menu'?this._menuPath:this._formParent).map(next_step_id=>({next_step_id})),wasForm=result.type==='form';this.uiHistory?.step(this,async()=>{await this.open(this.hass,this.entryId,route);if(wasForm&&this._open)this.content.insertAdjacentHTML('afterbegin','<p class="muted">Je eerdere invoer is niet teruggezet. Kies de instelling opnieuw; teruggaan of vooruitgaan slaat niets op.</p>');});}}catch(e){this.error.textContent=`Opslaan/volgende stap niet bevestigd: ${e.message||String(e)}. Controleer de werkelijke HA-instellingen vóór je opnieuw probeert.`;}finally{this._busy=false;this._controls(false);}}
  _text(text){const vars=this.flow?.description_placeholders||{};return String(text||'').replace(/\{([^}]+)\}/g,(m,k)=>String(vars[k]??m));}
  _render(){const f=this.flow||{},s=this.help.steps[f.step_id]||{};this.shadowRoot.querySelector('h2').textContent=s.title||'SolarPilot · configureren';const parent=f.type==='menu'?this._menuPath.slice(0,-1):this._formParent,back=this.shadowRoot.querySelector('.back');back.setAttribute('aria-label',f.step_id==='init'?'Terug naar SolarPilot':'Terug naar '+(this.help.steps[parent.at(-1)||'init']?.title||'instellingenoverzicht'));back.title=back.getAttribute('aria-label');if(f.type==='create_entry'||f.type==='abort'){this.flow=null;this._dirty=false;this._draftStarted=false;this.content.innerHTML=`<p>${spHelpEscape(f.type==='create_entry'?'Instellingen opgeslagen zonder volledige herlading. Wachtende voorstellen staan bij Toestellen beheren.':this.help.abort[f.reason]||f.reason||'Configuratie beëindigd.')}</p><button type="button" data-close>Sluiten</button>`;return;}
    const intro=`<p class="description">${spHelpEscape(this._text(s.description||''))}</p>`;
    if(f.type==='menu'){const menu=Array.isArray(f.menu_options)?f.menu_options:Object.keys(f.menu_options||{});this.content.innerHTML=intro+`<div class="menu">${menu.map(key=>`<button type="button" data-menu="${spHelpEscape(key)}">${spHelpEscape(s.menu_options?.[key]||this.help.steps[key]?.title||key)}</button>`).join('')}</div>`;return;}
    if(f.type!=='form'){this.content.innerHTML='<p>Dit type configuratiestap vereist de standaard Home Assistant-interface.</p>';return;}
    this._unsupported=false;const fields=(f.data_schema||[]).map((schema,index)=>this._field(schema,index,s)).join('');const base=f.errors?.base;this.content.innerHTML=intro+`<form>${fields}${base?`<p class="error">${spHelpEscape(this.help.errors[base]||base)}</p>`:''}<div class="actions"><button class="primary" type="submit" ${this._unsupported?'disabled data-permanent-disabled="1"':''}>Opslaan / verder</button><button type="button" data-close>Annuleren</button></div></form>`;}
  _field(schema,index,step){const key=schema.name, label=step.data?.[key]||key;const value=schema.description?.suggested_value??schema.default;const selector=schema.selector||{};const type=Object.keys(selector)[0]||schema.type||'string';const cfg=selector[type]||{};const req=schema.required?'required':'';const id=`option-${index}`;let control;
    if(type==='boolean')control=`<div class="check"><input id="${id}" name="${spHelpEscape(key)}" data-kind="boolean" type="checkbox" ${value?'checked':''}><span>Aan</span></div>`;
    else if(type==='number'||type==='integer'||type==='float')control=`<input id="${id}" name="${spHelpEscape(key)}" data-kind="number" type="number" value="${spHelpEscape(value??'')}" min="${spHelpEscape(cfg.min??schema.value_min??'')}" max="${spHelpEscape(cfg.max??schema.value_max??'')}" step="${spHelpEscape(cfg.step??(type==='integer'?1:'any'))}" ${req}>`;
    else if(type==='select'){const multi=!!cfg.multiple, raw=cfg.options||schema.options||[];const items=Array.isArray(raw)?raw:Object.entries(raw);const selected=multi?(Array.isArray(value)?value:[]):[value];const opts=items.map(o=>Array.isArray(o)?{value:o[0],label:o[1]}:typeof o==='object'?o:{value:o,label:o});control=`<select id="${id}" name="${spHelpEscape(key)}" data-kind="${multi?'multiple':'select'}" ${multi?'multiple size="4"':''} ${req}>${!multi?'<option value="">— kies —</option>':''}${opts.map(o=>`<option value="${spHelpEscape(o.value)}" ${selected.some(v=>String(v)===String(o.value))?'selected':''}>${spHelpEscape(o.label||o.value)}</option>`).join('')}</select>`;}
    else if(type==='entity'){const multi=!!cfg.multiple;let domains=cfg.domain||cfg.filter?.domain;const filters=Array.isArray(cfg.filter)?cfg.filter:cfg.filter?[cfg.filter]:[];const choices=Object.entries(this.hass.states||{}).filter(([entity,obj])=>{const domain=entity.split('.')[0];if(domains&&!([domains].flat()).includes(domain))return false;return !filters.length||filters.some(filter=>(!filter.domain||[filter.domain].flat().includes(domain))&&(!filter.device_class||[filter.device_class].flat().includes(obj.attributes?.device_class)));});const selected=multi?(Array.isArray(value)?value:[]):value?[value]:[];for(const entity of selected){if(!choices.some(([k])=>k===entity))choices.unshift([entity,{attributes:{friendly_name:'Huidige koppeling (niet in keuzelijst)'}}]);}choices.sort((a,b)=>String(a[1].attributes?.friendly_name||a[0]).localeCompare(String(b[1].attributes?.friendly_name||b[0])));if(multi)control=`<select id="${id}" name="${spHelpEscape(key)}" data-kind="multiple" multiple size="5" ${req}>${choices.map(([entity,obj])=>`<option value="${spHelpEscape(entity)}" ${selected.includes(entity)?'selected':''}>${spHelpEscape(obj.attributes?.friendly_name||entity)} · ${spHelpEscape(entity)}</option>`).join('')}</select>`;else control=`<input id="${id}" name="${spHelpEscape(key)}" data-kind="entity" list="${id}-choices" value="${spHelpEscape(value||'')}" placeholder="Zoek naam of entity_id" ${req}><datalist id="${id}-choices">${choices.map(([entity,obj])=>`<option value="${spHelpEscape(entity)}">${spHelpEscape(obj.attributes?.friendly_name||entity)}</option>`).join('')}</datalist>`;}
    else if(type==='time')control=`<input id="${id}" name="${spHelpEscape(key)}" data-kind="time" type="time" value="${spHelpEscape(String(value||'').slice(0,5))}" step="60" ${req}>`;
    else if(['text','string'].includes(type))control=`<input id="${id}" name="${spHelpEscape(key)}" data-kind="text" type="${cfg.type==='password'?'password':'text'}" value="${spHelpEscape(value??'')}" ${req}>`;
    else{this._unsupported=true;control='<p class="error">Gebruik de standaard Home Assistant-configuratie voor dit veldtype.</p>';}
    const explanation=this.help.entries[`${this.flow.step_id}.${key}`];const code=this.flow.errors?.[key];return `<div class="field"><div class="label"><label for="${id}">${spHelpEscape(label)}${schema.required?' *':''}</label><button class="help" type="button" data-help="${spHelpEscape(key)}" title="${spHelpEscape(explanation?.short||'Uitleg openen')}" aria-label="Uitleg bij ${spHelpEscape(label)}">?</button></div>${control}${code?`<p class="error inline-error">${spHelpEscape(this.help.errors[code]||code)}</p>`:''}</div>`;}
  _submit(form){if(this._busy||this._unsupported)return;try{if(!form.reportValidity())return;const values={};for(const el of form.querySelectorAll('input[name],select[name],textarea[name]')){const type=el.dataset.kind;let value=type==='boolean'?el.checked:type==='multiple'?Array.from(el.querySelectorAll('option:checked')).map(o=>o.value):el.value;if(value===''&&!el.required)continue;if(type==='number'){value=Number(value);if(!Number.isFinite(value)){this.error.textContent='Vul een geldig getal in.';return;}}if(type==='time'&&value.length===5)value+=':00';values[el.name]=value;}this._draftStarted=true;this._request(`config/config_entries/options/flow/${encodeURIComponent(this.flow.flow_id)}`,values);}catch(e){this.error.textContent='De invoer kon niet worden gelezen; niets opgeslagen. '+(e.message||String(e));}}
  _click(e){const button=e.target.closest('button');if(!button||button.disabled)return;if(button.hasAttribute('data-help')){e.preventDefault();this.uiHistory?.prepare();if(!this.helpDialog){this.helpDialog=document.createElement('solar-pilot-option-help-dialog');this.shadowRoot.append(this.helpDialog);}const step=this.flow.step_id,key=button.dataset.help;this.helpDialog.open(step,key);this.uiHistory?.track(this.helpDialog,()=>this.helpDialog.open(step,key));return;}if(button.hasAttribute('data-close'))this.close();if(button.hasAttribute('data-menu'))this._request(`config/config_entries/options/flow/${encodeURIComponent(this.flow.flow_id)}`,{next_step_id:button.dataset.menu});}
}
if(!customElements.get('solar-pilot-options-dialog'))customElements.define('solar-pilot-options-dialog',SolarPilotOptionsDialog);


/* This management view is read-only until a native validated options flow saves. */
class SolarPilotDeviceManagerDialog extends HTMLElement{
  constructor(){super();this.attachShadow({mode:'open'});this._open=false;this.shadowRoot.innerHTML=`<style>${spHelpStyle}.device{padding:15px 0;border-bottom:1px solid var(--divider-color,#606874)}.device h3{margin:0}.actions{margin-top:9px}.archive{opacity:.8}</style><dialog aria-label="Toestellen beheren"><header><h2>Toestellen beheren</h2><button class="close" aria-label="Toestelbeheer sluiten">×</button></header><div class="body"></div></dialog>`;this.dialog=this.shadowRoot.querySelector('dialog');this.shadowRoot.querySelector('.close').onclick=()=>this.close();this.shadowRoot.addEventListener('click',e=>this._click(e));this.dialog.addEventListener('cancel',e=>{e.preventDefault();this.close();});}
  open(hass,data){this.hass=hass;this._open=true;this._sig=null;this.update(data);this.dialog.showModal();}
  close(){this._open=false;this.dialog.close();}
  disconnectedCallback(){this.close();}
  update(data){this.data=data||{};if(!this._open)return;const sig=JSON.stringify(this.data);if(sig===this._sig)return;this._sig=sig;const scroll=this.dialog.scrollTop;const x=this.data;const admin=!!this.hass?.user?.is_admin;
    this.shadowRoot.querySelector('.body').innerHTML=`<p>Bekijken kan ook terwijl Automatisch regelen actief is. Gewone wijzigingen worden zonder volledige herlading toegepast. Koppelingen en bescherming van een lopende cyclus blijven staan tot veilig toepassen mogelijk is.</p><p class="muted">${spHelpEscape(x.status||'')}${x.error?' · '+spHelpEscape(x.error):''}</p>${admin?'<div class="actions"><button data-go="add" class="primary">Toestel toevoegen</button><button data-go="pending_changes">Wachtende wijzigingen</button></div>':''}
    ${(x.pending||[]).length?`<p class="description">${x.pending.map(p=>spHelpEscape(p.name)+': '+spHelpEscape(p.reason)).join('<br>')}</p>`:''}
    ${(x.devices||[]).map(d=>`<section class="device"><h3>${spHelpEscape(d.name)}</h3><p>${spHelpEscape(({dishwasher:'Afwasmachine',washing_machine:'Wasmachine',tumble_dryer:'Droogkast'})[d.appliance_type]||'Toestel')} · ${spHelpEscape(d.on?'Actief':d.mode==='disabled'?'Uitgesloten':'Auto')} ${d.pending?' · wijziging wacht':''}</p>${d.pending?'<p>'+spHelpEscape(d.pending)+'</p>':''}<div class="actions">${admin?`<button data-go="manage_device" data-id="${spHelpEscape(d.id)}" data-section="settings">Instellingen</button><button data-go="manage_device" data-id="${spHelpEscape(d.id)}" data-section="connections">Koppelingen</button><button data-go="manage_device" data-id="${spHelpEscape(d.id)}" data-section="planning">Planning</button>`:''}<button data-history="${spHelpEscape(d.id)}">Geschiedenis</button>${admin?`<button data-go="replace" data-id="${spHelpEscape(d.id)}">Vervangen</button>`:''}</div></section>`).join('')||'<p>Nog geen SolarPilot-toestellen toegevoegd.</p>'}
    ${(x.archives||[]).length?'<h3>Gearchiveerde toestellen</h3>':''}${(x.archives||[]).map(d=>`<section class="device archive"><strong>${spHelpEscape(d.name)}</strong><p>Geen bediening of starttoestemming. Bewaarde geschiedenis binnen de ingestelde termijn; eerdere leergegevens staan in de analyse-export.</p><button data-history="${spHelpEscape(d.id)}">Bewaarde geschiedenis</button></section>`).join('')}
    <p class="muted">De categorie wasmachine/droogkast verleent geen merkspecifieke startrechten. Kies en controleer een ondersteunde koppeling. Vervangen maakt een nieuw profiel zonder oude meters, startrechten of leergegevens.</p>`;this.dialog.scrollTop=scroll;}
  _click(e){const b=e.target.closest('button');if(!b)return;if(b.dataset.go){if(!this.hass?.user?.is_admin)return;const detail={step:b.dataset.go,id:b.dataset.id,section:b.dataset.section};this.close();this.dispatchEvent(new CustomEvent('device-options',{detail}));}else if(b.dataset.history){const d=[...(this.data.devices||[]),...(this.data.archives||[])].find(d=>d.id===b.dataset.history);this.close();if(d)this.dispatchEvent(new CustomEvent('device-history',{detail:d}));}}
}
if(!customElements.get('solar-pilot-device-manager-dialog'))customElements.define('solar-pilot-device-manager-dialog',SolarPilotDeviceManagerDialog);
